name: Feature request
description: Propose a feature or enhancement
title: ""
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      value: ""
      required: true
  - type: markdown
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      value: ""
      required: true
  - type: markdown
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of what you want to happen."
      value: ""
  - type: markdown
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
      value: ""
